### ISSUE TITLE
Adding Forms for GIT Github Event

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-io/forms.cyberbuddy.io#11]
@lovishprabhakar02 
@pacific-prashant 
@logic-404

You can add your forms over here. Just reference them to this issue.

**Comment by logic-404** [comment]
Cool Guys !! Checout the timings of this comment LOL

**Comment by cyberbuddy-manas** [comment]
Hi @logic-404 @lovishprabhakar02 you guys can close your forms by adding onload="start()" inside body attributes.
